/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmtpSettingsRouteImport } from './routes/smtp-settings'
import { Route as SentRouteImport } from './routes/sent'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as OutboxRouteImport } from './routes/outbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FiltersRouteImport } from './routes/filters'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as ComposeRouteImport } from './routes/compose'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailsIdRouteImport } from './routes/emails.$id'

const SmtpSettingsRoute = SmtpSettingsRouteImport.update({
  id: '/smtp-settings',
  path: '/smtp-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SentRoute = SentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const OutboxRoute = OutboxRouteImport.update({
  id: '/outbox',
  path: '/outbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FiltersRoute = FiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeRoute = ComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsIdRoute = EmailsIdRouteImport.update({
  id: '/emails/$id',
  path: '/emails/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/compose': typeof ComposeRoute
  '/drafts': typeof DraftsRoute
  '/filters': typeof FiltersRoute
  '/login': typeof LoginRoute
  '/outbox': typeof OutboxRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/sent': typeof SentRoute
  '/smtp-settings': typeof SmtpSettingsRoute
  '/emails/$id': typeof EmailsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/compose': typeof ComposeRoute
  '/drafts': typeof DraftsRoute
  '/filters': typeof FiltersRoute
  '/login': typeof LoginRoute
  '/outbox': typeof OutboxRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/sent': typeof SentRoute
  '/smtp-settings': typeof SmtpSettingsRoute
  '/emails/$id': typeof EmailsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/compose': typeof ComposeRoute
  '/drafts': typeof DraftsRoute
  '/filters': typeof FiltersRoute
  '/login': typeof LoginRoute
  '/outbox': typeof OutboxRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/sent': typeof SentRoute
  '/smtp-settings': typeof SmtpSettingsRoute
  '/emails/$id': typeof EmailsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/compose'
    | '/drafts'
    | '/filters'
    | '/login'
    | '/outbox'
    | '/preferences'
    | '/profile'
    | '/sent'
    | '/smtp-settings'
    | '/emails/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/compose'
    | '/drafts'
    | '/filters'
    | '/login'
    | '/outbox'
    | '/preferences'
    | '/profile'
    | '/sent'
    | '/smtp-settings'
    | '/emails/$id'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/compose'
    | '/drafts'
    | '/filters'
    | '/login'
    | '/outbox'
    | '/preferences'
    | '/profile'
    | '/sent'
    | '/smtp-settings'
    | '/emails/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  ComposeRoute: typeof ComposeRoute
  DraftsRoute: typeof DraftsRoute
  FiltersRoute: typeof FiltersRoute
  LoginRoute: typeof LoginRoute
  OutboxRoute: typeof OutboxRoute
  PreferencesRoute: typeof PreferencesRoute
  ProfileRoute: typeof ProfileRoute
  SentRoute: typeof SentRoute
  SmtpSettingsRoute: typeof SmtpSettingsRoute
  EmailsIdRoute: typeof EmailsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/smtp-settings': {
      id: '/smtp-settings'
      path: '/smtp-settings'
      fullPath: '/smtp-settings'
      preLoaderRoute: typeof SmtpSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sent': {
      id: '/sent'
      path: '/sent'
      fullPath: '/sent'
      preLoaderRoute: typeof SentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outbox': {
      id: '/outbox'
      path: '/outbox'
      fullPath: '/outbox'
      preLoaderRoute: typeof OutboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filters': {
      id: '/filters'
      path: '/filters'
      fullPath: '/filters'
      preLoaderRoute: typeof FiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose': {
      id: '/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails/$id': {
      id: '/emails/$id'
      path: '/emails/$id'
      fullPath: '/emails/$id'
      preLoaderRoute: typeof EmailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  ComposeRoute: ComposeRoute,
  DraftsRoute: DraftsRoute,
  FiltersRoute: FiltersRoute,
  LoginRoute: LoginRoute,
  OutboxRoute: OutboxRoute,
  PreferencesRoute: PreferencesRoute,
  ProfileRoute: ProfileRoute,
  SentRoute: SentRoute,
  SmtpSettingsRoute: SmtpSettingsRoute,
  EmailsIdRoute: EmailsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
