// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Relate.Smtp.Infrastructure.Data;

#nullable disable

namespace Relate.Smtp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129023049_AddUserPreferences")]
    partial class AddUserPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Relate.Smtp.Core.Entities.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromDisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TextBody")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("ReceivedAt");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("Relate.Smtp.Core.Entities.EmailAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmailId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmailId");

                    b.ToTable("EmailAttachments");
                });

            modelBuilder.Entity("Relate.Smtp.Core.Entities.EmailFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignLabelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyContains")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Delete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromAddressContains")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("HasAttachments")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastAppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MarkAsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectContains")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesApplied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignLabelId");

                    b.HasIndex("UserId", "Priority");

                    b.ToTable("EmailFilters");
                });

            modelBuilder.Entity("Relate.Smtp.Core.Entities.EmailLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmailId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LabelId");

                    b.HasIndex("EmailId", "LabelId")
                        .IsUnique();

                    b.HasIndex("UserId", "LabelId");

                    b.ToTable("EmailLabels");
                });

            modelBuilder.Entity("Relate.Smtp.Core.Entities.EmailRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmailId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Address");

                    b.HasIndex("EmailId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("EmailRecipients");
                });

            modelBuilder.Entity("Relate.Smtp.Core.Entities.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("Relate.Smtp.Core.Entities.SmtpApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RevokedAt");

                    b.HasIndex("UserId");

                    b.ToTable("SmtpApiKeys");
                });

            modelBuilder.Entity("Relate.Smtp.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OidcIssuer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OidcSubject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("OidcIssuer", "OidcSubject")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Relate.Smtp.Core.Entities.UserEmailAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Address");

                    b.HasIndex("UserId", "Address")
                        .IsUnique();

                    b.ToTable("UserEmailAddresses");
                });

            modelBuilder.Entity("Relate.Smtp.Core.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultSort")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DesktopNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DigestFrequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("DigestTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayDensity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailDigest")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmailsPerPage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GroupByDate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowPreview")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Relate.Smtp.Core.Entities.EmailAttachment", b =>
                {
                    b.HasOne("Relate.Smtp.Core.Entities.Email", "Email")
                        .WithMany("Attachments")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");
                });

            modelBuilder.Entity("Relate.Smtp.Core.Entities.EmailFilter", b =>
                {
                    b.HasOne("Relate.Smtp.Core.Entities.Label", "AssignLabel")
                        .WithMany()
                        .HasForeignKey("AssignLabelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Relate.Smtp.Core.Entities.User", "User")
                        .WithMany("EmailFilters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignLabel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Relate.Smtp.Core.Entities.EmailLabel", b =>
                {
                    b.HasOne("Relate.Smtp.Core.Entities.Email", "Email")
                        .WithMany("EmailLabels")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relate.Smtp.Core.Entities.Label", "Label")
                        .WithMany("EmailLabels")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relate.Smtp.Core.Entities.User", "User")
                        .WithMany("EmailLabels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("Label");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Relate.Smtp.Core.Entities.EmailRecipient", b =>
                {
                    b.HasOne("Relate.Smtp.Core.Entities.Email", "Email")
                        .WithMany("Recipients")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relate.Smtp.Core.Entities.User", "User")
                        .WithMany("ReceivedEmails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Email");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Relate.Smtp.Core.Entities.Label", b =>
                {
                    b.HasOne("Relate.Smtp.Core.Entities.User", "User")
                        .WithMany("Labels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Relate.Smtp.Core.Entities.SmtpApiKey", b =>
                {
                    b.HasOne("Relate.Smtp.Core.Entities.User", "User")
                        .WithMany("SmtpApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Relate.Smtp.Core.Entities.UserEmailAddress", b =>
                {
                    b.HasOne("Relate.Smtp.Core.Entities.User", "User")
                        .WithMany("AdditionalAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Relate.Smtp.Core.Entities.UserPreference", b =>
                {
                    b.HasOne("Relate.Smtp.Core.Entities.User", "User")
                        .WithOne("Preference")
                        .HasForeignKey("Relate.Smtp.Core.Entities.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Relate.Smtp.Core.Entities.Email", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("EmailLabels");

                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("Relate.Smtp.Core.Entities.Label", b =>
                {
                    b.Navigation("EmailLabels");
                });

            modelBuilder.Entity("Relate.Smtp.Core.Entities.User", b =>
                {
                    b.Navigation("AdditionalAddresses");

                    b.Navigation("EmailFilters");

                    b.Navigation("EmailLabels");

                    b.Navigation("Labels");

                    b.Navigation("Preference");

                    b.Navigation("ReceivedEmails");

                    b.Navigation("SmtpApiKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
